### ISSUE TITLE
Can't resolve example DID on dev.uniresolver.io

### ISSUE THREAD

**Issue by BernhardFuchs** [decentralized-identity/uni-resolver-driver-did-ion#30]
When trying to resolve the example DID `did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w` on dev.uniresolver.io following error is returned:
```
[notFound] 404 Not Found ({"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"|6909e1e2-4d1fb5f869082fa0."})
```

In the uni-resolver we can see following error:
```
2024-06-03T07:31:40,861 WARN  [qtp947437179-54] u.w.s.ResolveServlet: Resolve problem for did:ion:EiClkZMDxPKqC9c-umQfTkR8vvZ9JPhl_xLDI9Nfk38w5w: 404 Not Found ({"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"|6909e1a7-4d1fb5f869082fa0."})
uniresolver.ResolutionException: 404 Not Found ({"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"|6909e1a7-4d1fb5f869082fa0."})
	at uniresolver.driver.http.HttpDriver.resolveRepresentation(HttpDriver.java:139)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentationWithDrivers(LocalUniResolver.java:167)
	at uniresolver.local.LocalUniResolver.resolveOrResolveRepresentation(LocalUniResolver.java:123)
	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:73)
	at uniresolver.local.LocalUniResolver.resolveRepresentation(LocalUniResolver.java:68)
	at uniresolver.web.WebUniResolver.resolveRepresentation(WebUniResolver.java:56)
	at uniresolver.web.servlet.ResolveServlet.doGet(ResolveServlet.java:92)
```

The driver logs start with the same error as described in this [issue](#27 )

**Comment by lemoustachiste** [comment]
same issue occurring with the main resolver (https://resolver.identity.foundation/) both API and Browser

**Comment by lemoustachiste** [comment]
just saw that the uni resolver calls the `dev` resolver anyway.

**Comment by lemoustachiste** [comment]
Could it be related to this url being unavailable: https://github.com/decentralized-identity/uni-resolver-driver-did-ion/blob/master/src/config.json#L14C17-L14C73?

as per this issue: https://github.com/decentralized-identity/ion/issues/328

And more globally does that mean that did:ion is dead?

**Comment by peacekeeper** [comment]
> Could it be related to this url being unavailable

Yes probably. If anyone is aware of a public ION node endpoint, feel free to create a PR to update this configuration.

> And more globally does that mean that did:ion is dead?

This is a matter of perspective. When is a decentralized network "dead"? :)

Anyone can run an ION node. On our Godiddy platform, did:ion is alive: https://godiddy.com/
